In [5]:
d= 23
l = 2
num = d*l
print(num)


46


In [13]:
import numpy as np
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array


array([1, 2, 3, 4, 5])

In [16]:
print("ID Array \t", my_array)
print("Shape: ", my_array.shape)
print("Rank:", my_array.ndim)
print("size:", my_array.size)
print("Data type: ", my_array.dtype)

ID Array 	 [1 2 3 4 5]
Shape:  (5,)
Rank: 1
size: 5
Data type:  int32


In [21]:
# for nested lists
my_list2 = ([ [1,2,3,4], [2.,3.,6.,4], [2,-2,4,-7] ])
Arra = np.array(my_list2)
Arra

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  6.,  4.],
       [ 2., -2.,  4., -7.]])

In [20]:
print("3D Array \n", Arra)

3D Array 
 [[[ 1.  2.  3.  4.]]

 [[ 2.  3.  6.  4.]]

 [[ 2. -2.  4. -7.]]]


In [24]:
print("Shape : ", Arra.shape)
print("Size: ", Arra.size)
print("Rank: ", Arra.ndim)
print("Data Type:", Arra.dtype)
# just like solving matrix, the above array is a 3x4 matrix,
# to know what matrix it is, we use the function shape.
# to know the numbers of value in the matrix, we use the size function.
# to the rank or should i say the number of lists we use the ndim function
# lastly, but not the least though, we use the dtype function.
# Omo... Naa God oo

Shape :  (3, 1, 4)
Size:  12
Rank:  3
Data Type: float64


In [40]:
# We are using the arange to assign values in a particular range to a variable
nums = np.arange(20)
number = (nums+1)
print(f"Nums:   {nums}, \nNumber: {number}")
# As you know reading of numbers start from Zero, So i added 1 to it so when printing it wil start from 1 and not zero

Nums:   [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], 
Number: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
print(nums.dtype)
print(type(nums))

int32
<class 'numpy.ndarray'>


In [44]:
# now just like we mention earlier about matrix...the above variable nums has a matrix of 1x20 matrix
# let assume we need to reshape the matrix or after generating the values we need to assign it to a matrix, 
# then we can use the reshape function just like this

reshaped = number.reshape(2,2,5)
print(reshaped)
print(reshaped.dtype)
print(type(reshaped))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
int32
<class 'numpy.ndarray'>


In [26]:
# Now we move to filling a list with a unique identity
all_zeros = np.zeros((2,3))
print(all_zeros)
# For just one
all_ones = np.ones((2,3))
print('\n',all_ones)
'''
gbo = all_zeros.append(all_ones)
print(all_zeros)
'''
# To do the same for any other values you use the function full, like this
all_full = np.full((2,5), 3)
print('\n',all_full)

[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]]


In [25]:
import numpy as np
# the random function adds random values to an array 
rn = np.random.random((2,5))
print(f'Grenerating Random values \n{rn}')


# creating an empty array
# Just like the zero function, empty function performs the functions of zeros funtion.
em = np.empty((2,3))
print(f'Empty Array\n{em}')


#then also the linspace function..
# it space values within a range i.e let assume we are assigning values in range of 0-2 to an array and we want to have the size to be about 9 values, 
# we use the linspace function like this
lin = np.linspace(0,2, 10)
print(lin)


# But i discovered something
nh = np.linspace((0,2),9)
nh

Grenerating Random values 
[[0.85154272 0.48429858 0.40117782 0.94861401 0.59751011]
 [0.18838118 0.00754451 0.68035505 0.46527027 0.86892876]]
Empty Array
[[0. 0. 0.]
 [0. 0. 0.]]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


array([[0.        , 2.        ],
       [0.18367347, 2.14285714],
       [0.36734694, 2.28571429],
       [0.55102041, 2.42857143],
       [0.73469388, 2.57142857],
       [0.91836735, 2.71428571],
       [1.10204082, 2.85714286],
       [1.28571429, 3.        ],
       [1.46938776, 3.14285714],
       [1.65306122, 3.28571429],
       [1.83673469, 3.42857143],
       [2.02040816, 3.57142857],
       [2.20408163, 3.71428571],
       [2.3877551 , 3.85714286],
       [2.57142857, 4.        ],
       [2.75510204, 4.14285714],
       [2.93877551, 4.28571429],
       [3.12244898, 4.42857143],
       [3.30612245, 4.57142857],
       [3.48979592, 4.71428571],
       [3.67346939, 4.85714286],
       [3.85714286, 5.        ],
       [4.04081633, 5.14285714],
       [4.2244898 , 5.28571429],
       [4.40816327, 5.42857143],
       [4.59183673, 5.57142857],
       [4.7755102 , 5.71428571],
       [4.95918367, 5.85714286],
       [5.14285714, 6.        ],
       [5.32653061, 6.14285714],
       [5.

In [20]:
# remember appending lists to another..yeah this is just like that
# making multiple list into a single list using the flatten function.
add = np.array([[1,2,3], [3,3,2],[2,3,1]])
flar = add.flatten()
flar

array([1, 2, 3, 3, 3, 2, 2, 3, 1])

In [27]:
# To do the same for any other values you use the full function, like this, also making the values in complex format.
all_full = np.full((2,3), 3, dtype=complex)
print('\n',all_full)


 [[3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j]]


In [35]:
print(add[2][2])
# indexing
# Let assign a new value to it
add[2][2]= 3
add

1


array([[1, 2, 3],
       [3, 3, 2],
       [2, 3, 3]])

In [37]:
print(all_full[1][2])
# indexing
all_full[1][2]=4
all_full

(3+0j)


array([[3.+0.j, 3.+0.j, 3.+0.j],
       [3.+0.j, 3.+0.j, 4.+0.j]])

In [50]:
# Slicing

a = np.random.random((2,4))
print(a)

aa = a[1:3, 1:3]
print(aa)

c = a.flatten()
ca = c[1:3]
print(ca)

b = np.array([1,2,3,4,6])
ab = b[1:3]
ab

[[0.39166014 0.42043444 0.47038074 0.3148193 ]
 [0.82626625 0.94136321 0.67309872 0.32927718]]
[[0.94136321 0.67309872]]
[0.42043444 0.47038074]


array([2, 3])

In [15]:
import numpy as np
king = np.arange(32).reshape(4,8)
print(king + 1)

# So i discovered this from a syntax from an error message , actually it two, .all() and .any(), guess they perform same funtion.
if king.all() <= 20:
    print("Small")

for i in king <= 20:
    print('small')
    
king < 20

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]
Small
small
small
small
small


array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [16]:
king[ king < 20 ]
# getting the values which is less than 20 from the generated array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# Also numpy can perform maths functions as well.
# like the add, subtract, multiply, divede, sqrt functions and the likes
x = np.arange(0,4).reshape(2,2)
y = np.arange(5,9).reshape(2,2)

add = np.add(x,y)
add
# likewise the other functions 
# when it comes to sqrt, one positional value is passed.


array([[ 5,  7],
       [ 9, 11]])

In [24]:
# Transpose of a matrix, using the .T function
arr = np.arange(10).reshape(2,5)
print(arr)

# Tranpose
Tarr =arr.T
print()
print(f'Transpose: \n{Tarr}')

[[0 1 2 3 4]
 [5 6 7 8 9]]

Transpose: 
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [25]:
# multiplying the matrix and the transpose
mut = np.dot(Tarr, arr)
mut

array([[25, 30, 35, 40, 45],
       [30, 37, 44, 51, 58],
       [35, 44, 53, 62, 71],
       [40, 51, 62, 73, 84],
       [45, 58, 71, 84, 97]])

In [39]:
ary = 10 * np.random.randn(2,5)
print(ary)
print()
# Just like the pandas function, to calculate mean, Max, median, std, 
print(f"Mean : {np.mean(ary)}")
print(f"STD : {np.std(ary)}")
print(f"Median : {np.median(ary)}")
print(f"Max : {np.max(ary)}")
print(f"Min : {np.min(ary)}")
print(f"AvgMin : {np.argmin(ary)}")
print(f"AvgMax : {np.argmax(ary)}")


[[ 1.60150759 -5.5181706   0.66098417 -7.49469946 -1.63196323]
 [-0.80071822 -8.00466249 -3.73420082 18.7995839  -8.29967963]]

Mean : -1.4422018785001494
STD : 7.566077971274948
Median : -2.6830820240706528
Max : 18.79958390248895
Min : -8.299679632040151
AvgMin : 9
AvgMax : 8
